### ISSUE TITLE
AttributeError occured

### ISSUE THREAD

**Issue by canpc815** [aws-samples/amazon-cloudfront-with-s3-multi-region-access-points#1]
Dear lovaarte,

I got this message when I deployed in Lambda.
But there's no problem when I executed  lambda_handler function in local env.
Would you please help me addressing this problem?

[ERROR] AttributeError: module 'botocore.crt' has no attribute 'auth'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 65, in lambda_handler
    auth_headers = SigV4AWrapper().get_auth_headers(method, endpoint, data, region, service, cf_read_only_headers)
  File "/var/task/lambda_function.py", line 24, in get_auth_headers
    sigv4a = crt.auth.CrtS3SigV4AsymAuth(self._session.get_credentials(), service, region)

**Comment by canpc815** [comment]
I've confirmed that there's no problem in Lambda@Edge using Python 3.7 env.

**Comment by vincentclee** [comment]
Lambda@Edge using Python 3.9 works also.

**Comment by lovaarte** [comment]
Closing as this seems to be resolved.
